language: ruby
rvm:
  - 2.5.3
  - 2.6.0
  - 2.7.2
services:
  - docker
env:
  - DB=postgresql
before_install:
  - docker run --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 -d postgres:11.7
  - sleep 2 # gives postgresql some time to boot
  - cp spec/config.travis.yml spec/config.yml
  - psql -c 'create database textacular_test' -U postgres -h localhost
script:
  - bundle exec rake db:migrate
  - bundle exec rake
gemfile:
  - Gemfile
  - gemfiles/activerecord-5.0.gemfile
  - gemfiles/activerecord-5.1.gemfile
  - gemfiles/activerecord-5.2.gemfile
  - gemfiles/activerecord-6.0.gemfile
  - gemfiles/activerecord-6.1.gemfile

jobs:
  exclude:
  - rvm: 2.5.3
    gemfile: Gemfile
  - rvm: 2.6.0
    gemfile: Gemfile
