language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
env:
  - DB=postgresql
before_install:
  - cp spec/config.travis.yml spec/config.yml
  - psql -c 'create database textacular_test' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake
gemfile:
  - Gemfile
  - gemfiles/activerecord-5.0.gemfile
  - gemfiles/activerecord-5.1.gemfile
  - gemfiles/activerecord-5.2.gemfile
