language: ruby
rvm:
  - 2.5.3
  - 2.6.0
services:
  - postgresql
addons:
  postgresql: 9.6
env:
  - DB=postgresql
before_install:
  - cp spec/config.travis.yml spec/config.yml
  - psql -c 'create database textacular_test' -U postgres -h localhost
script:
  - bundle exec rake db:migrate
  - bundle exec rake
gemfile:
  - Gemfile
  - gemfiles/activerecord-5.0.gemfile
  - gemfiles/activerecord-5.1.gemfile
  - gemfiles/activerecord-5.2.gemfile
  - gemfiles/activerecord-6.0.gemfile
