name: Main
on:
  push:

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0]
    name: Gemfile - Ruby ${{ matrix.ruby }}
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: textacular_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports: ["5432:5432"]
    env:
      BUNDLE_GEMFILE: Gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup database
        run: |
          cp spec/config.github.yml spec/config.yml
          bundle exec rake db:migrate

      - name: Run tests
        run: bundle exec rake

  versions:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: textacular_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports: ["5432:5432"]
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]
        rails: ['5.0', '5.1', '5.2', '6.0', '6.1']
        include:
          - rails: '7.0'
            ruby: '2.7'
          - rails: '7.0'
            ruby: '3.0'
          - rails: '7.0'
            ruby: '3.1'

    name: Ruby ${{ matrix.ruby }} - Rails ${{ matrix.rails }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/activerecord-${{ matrix.rails }}.gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup database
        run: |
          cp spec/config.github.yml spec/config.yml
          bundle exec rake db:migrate

      - name: Run tests
        run: bundle exec rake
